version: "3"
services:
  jupyter:
    container_name: "tensorflow-notebook"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./homework:/home/jovyan/work
